### ISSUE TITLE
Standardify qt

### ISSUE THREAD

**Issue by dnomadb** [mapbox/make-surface#79]
The qt (QuadTri) is the modified quadtree index value we are basing all triangle work on. It has gone by many names since its inception. We need to standardize its use here and in https://github.com/mapbox/trizilla/
- [x] `quadtree --> qt` (unless actually quadtree)
- [x] `index --> qt` (unless actually another kind of index)
- [x] `quadtri --> qt`
- [x] `otherrandomthingswevecalledit --> qt`

cc: @ian29

**Comment by dnomadb** [comment]
Done in https://github.com/mapbox/make-surface/pull/81

**Comment by ian29** [comment]
@dnomadb is post-#81 makesurface published? im still seeing `fillfacets` output "key" instead of "qt"

**Comment by ian29** [comment]
o is it bc of this? https://github.com/mapbox/make-surface/blob/master/makesurface/scripts/fill_facets.py#L90 

if so i can PR

**Comment by dnomadb** [comment]
Fixed with https://github.com/mapbox/make-surface/pull/83
SRY! :<
